### ISSUE TITLE
Origination fields in GCIS

### ISSUE THREAD

**Issue by abuddenb** [USGCRP/gcis#498] opened 2017-02-07 19:41 UTC
In the metadata surveys, we capture a family of fields descended from "Origination" with values 'Directly Cited', 'Adapted', 'Redrawn', and 'Original for Report'.

For instance, if a figure is "Redrawn" the next two questions are a free-form "How?" and then a citation.

We want to display the origination field and the responses to questions that follow from the selection through Angel's javascript UI.

Is there a place in GCIS to represent that data?

**Comment by amruelama** [comment] 2017-02-08 16:16
@abuddenb Currently in GCIS, if a figure is redrawn, we add both figures, then add their methodology of how one was derived from another as an 'activity' and add their provenance. Figure source is written in the field 'caption' whereas citation can be added in the field 'source citation' of a 'figure' directly. If the citation is related to the activity of the relationship between the figures, then it should be cited under one of these fields in [this](https://docs.google.com/spreadsheets/d/1E8B1mcgGg4ALxv7k9R6k3BeitopkTSh9A513iPGqpJY/edit#gid=0) spreadsheet (sheet - Activity). 

Does it makes sense?

Here is a best example of a figure derived from multiple datasets using multiple activities. You can notice the citation of origination under each activity is added under 'notes' field - https://data.globalchange.gov/activity/nca3-wildfire-smoke-widespread-health-effects-activity-1

**Comment by abuddenb** [comment] 2017-02-24 17:37
Just noting that we talked about this in a Hangout (2/23). @lomky started a thread in Slack to discuss specifics with Angel.

**Comment by lomky** [comment] 2017-03-15 17:52
Summing up a conversation in Slack:
 - Add a field to the Figure table of type json
 - Expose this field via RESTful API: at `/report/{report_id}/chapter/{chapter_id}/figure/{figure_id}/original.json`
 
Notes from me:
  - this field should not be exposed in the normal api
  - data does not need to be kept private in any way

The initial implementation will hopefully make way eventually to full integration with the GCIS Data Model.

**Comment by abuddenb** [comment] 2017-03-15 18:08
There will be multiple versions of our survey results (in JSON)--which is why we're asking for a catch-all vs specific fields. Here's an example of the first version:

```
{"nid":"3664","copyright":"original_work_nr","t1":{"version":1,"poc":"Kenneth E. Kunkel","poc_email":"Ken.Kunkel@noaa.gov","figure":{"figure_id":"","graphics_title":"2. Observed Spring Temperature","graphics_create_date":"2015-04-13 00:00:00","period_record":["1895-01-01","2014-12-31"],"spatial_extent":["36.9701","42.5084","-87.4952","-91.5129"],"origination":"Original","original_agency":"Kenneth E. Kunkel CICSNC\/NCEI","original_email":"Ken.Kunkel@noaa.gov"},"same_images":"Yes","n_images":"1","n_datasets":"1","datasets":[{"dataset_name":"U.S. Climate Divisional Dataset Version 2","imageSelect":["on"],"dataset_url":"https:\/\/www.ncdc.noaa.gov\/monitoring-references\/maps\/us-climate-divisions.php"}]},"t2":{"datasets":[],"methods":[{"version":1,"image_name":"2. Observed Spring Temperature","dataset":"U.S. Climate Divisional Dataset Version 2","dataset_modified":"No","dataset_location":"","dataset_modified_archived":"","dataset_need_archived":"","dataset_methods_used":"- Annual mean spring temperature (March - May) for the state was calculated for the full time period.\n- Annual mean spring temperature was calculated for each five-year period.","dataset_how_visualized":"Five-year average frequencies were plotted around the mean for the full-time period.","dataset_methods_published":"No","dataset_full_citation":"","dataset_authoritative_source":"Kenneth E. Kunkel CICSNC\/NCEI","dataset_software_used":["R version 3.1.3","","","","","","",""],"dataset_visualization_software":["Microsoft Office Excel 2007","","","","","","",""],"dataset_os_used":"Windows 7 (64 bit Operating System)","dataset_creation_time":"000:15","dataset_output_file":"CICS computer cluster \/snfs4\/assessment\/state summaries","dataset_files":["state.ave.tave.txt ","Code yearly and seasonal tave missing removed.doc","Regression p-values all states FINAL RESULTS.xls","","","","",""]}]},"filepath":"sites\/default\/files\/il_obs-spring-temp_v1_2.png"}
```
Here's a more recent iteration:

```
{
  "_id": "xxx",
  "project_identifier": "climate-science-special-report",
  "graphicId": "xxx",
  "overview_section": {
    "graphics_id": "xxx",
    "graphics_title": "Detection and attribution assessment of trends in average annual temperature (°F). - Panel: 3",
    "n_images": 1,
    "pocs": [
      {
        "name": "Someone",
        "organization": "NOAA",
        "email": "someone@noaa.gov"
      }
    ]
  },
  "origin_section": {
    "origination": "Adapted",
    "adapted": {
      "how": "Updated through 2015 (vs. 2012 in the original publication).",
      "publication": {
        "publication_type": "Journal Article",
        "citation": "My citation here"
      }
    }
  },
  "userId": "xxx",
  "modDate": "2016-11-18T17:31:47.870Z"
}
```

**Comment by lomky** [comment] 2017-03-17 19:15
- `_origination` field added to Figure
    - seems to be ignored by Figure API by default, to be confirmed.
 - GET path created. [Example on data-review](https://data-review.globalchange.gov/report/nca3/chapter/transportation/figure/role-of-adaptive-strategies-and-tactics-in-reducing-impacts-and-consequences/original.json) (limited access server)
    - `json` only
 - POST path in progress
   - currently dummy path accepts connects and responds with the payload,
   - no DB interaction yet.
   - requires auth'd user interaction.

**Comment by lomky** [comment] 2017-03-21 12:38
Code Complete excepting tests on the new API route. Moving into review and assigning to @abuddenb 

Remaining Steps:

 - [ ] Set tests for POST and GET of `original.json` path
 - [ ] TSU/Andrew approval of implementation
 - [ ] Follow on ticket for [long-term] mapping to `Activity`

**Comment by lomky** [comment] 2017-03-22 18:55
Added better Server handling for bad POST content and a DELETE path after conversing with Andrew.

**Comment by abuddenb** [comment] 2017-03-23 12:22
I think this is in a good place. Angel is going to develop the new metadata viewer against this new endpoint on data-review; that should shake out any critical bugs.

Once he's done and we're all agreed we can probably roll this out to production. I don't have credentials there, so we'll need to talk about moving data from somewhere else.

**Comment by lomky** [comment] 2017-03-23 12:54
@abuddenb Production content is loaded into Stage and then pushed to production, so I think the steps look like this: 

  1. Kat builds a Code Release with the new paths
  1. Kat pushes the Code Release to Stage & Production
  1. Andrew(?) updates data on Stage (now that the paths there are valid)
  1. Amrutha reviews Stage and does a Content Push to Production

And then the data will be live.

**Comment by lomky** [comment] 2017-03-23 13:03
Documented the basics of this [API on the internal wiki](https://github.com/USGCRP/gcis-internal/wiki/Origination-API-Documentation).

**Comment by abuddenb** [comment] 2017-04-05 17:54
@amruelama Data loaded to stage.

**Comment by amruelama** [comment] 2017-04-06 15:44
@abuddenb @lomky The content push is done and you should see the changes in production now, which closes this ticket.

**Closed by amruelama** 2017-04-06 15:44 UTC
Labels: context Front End, context Tuba API Changes, priority high, type content
